version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - type: cache-restore
        key: rails-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install postgresql-client

      - type: cache-save
        key: rails-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            echo bundle exec rake db:structure:load
      - run:
          name: rspec
          command: bundle ex rspec spec
      - type: store_test_results
        path: /tmp/test-results
